### ISSUE TITLE
App Homepage

### ISSUE THREAD

**Issue by dylanconnolly** [M4-Cross-Poll/frontend#2]
As a user, when I open the application I should see: 

- [x] A greeting message and Todays Date
- [x] The weather for my home/current location (Current might need to be an extension)
- [x] A button to create a new Scheduled Activity
- [x] A list of all upcoming activities
- [x] Pull data from API

When I select the Create New Activity button, it should take me to a form screen.

When I select an activity, it should take me to that activity's information.

**Comment by grayson-palmer** [comment]
Basic structure has been created. Still needs to be plugged in to APIs, and refined styling still necessary.
