### ISSUE TITLE
Create New Activity

### ISSUE THREAD

**Issue by dylanconnolly** [M4-Cross-Poll/frontend#3]
As a user on the app homepage I see a button to create a new activity. When clicked, I am taken to a new screen where I see a form.

In the form I can:
- [x] Select an activity from a dropdown menu
- [x] Input location where I will perform the activity
- [x] input a date on which I plan to perform the activity
- [x] A create activity button
- [x] Submit data to API on button click

When I select the Create Activity button, I should be taken to the [insert screen name here] screen

**Comment by grayson-palmer** [comment]
Basic layout and styling is completed. Need to set so will push to the API endpoint on submission.
